### ISSUE TITLE
Arduino simulation for ShiftOut library 😀

### ISSUE THREAD

**Issue by matititam** [InfectedBytes/ArduinoShiftOut#2]
Hi there

Please find the link for the Arduino ShiftOut project as well. 
The link is a permanent link and it will never be changed

https://wokwi.com/arduino/projects/309634438248006209

Thank you for the useful library again. 

I would love to hear from you about the improvement one can make so that the Simulator can help people like you who crate useful libraries for all!

Thank you!
Matititam

**Comment by InfectedBytes** [comment]
done 😄

**Comment by matititam** [comment]
Thanks a lot. Feel free to visit a growing community of Wokwi users here https://wokwi.com/discord
